ktor:
  development: true
  application:
    modules:
      - net.hennabatch.dojinapi.ApplicationKt.module
    deployment:
      port: 8080

dojinapi:
  db:
    url: "jdbc:postgresql://localhost:5432/DOJINLIB?currentSchema=djla"
    userName: "user"
    password: "localuserpass"
  jwt:
    audience: "tf4sz63y05faqvudp3ao0ogtir"
    issuer: "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_c40db9b4885f4e6682b6d2c5fa5d3100"