ktor:
  development: true
  application:
    modules:
      - net.hennabatch.dojinapi.Application.module
    deployment:
      port: 8080

dojinapi:
  init:
    cognito:
      region: ap-northeast-1
      userPoolName: DojinAPIUserPool
      endpoint: http://localhost:5000
      userName: localtest
      userEmail: localtest@hennabatch.net
      userPassword: Tes7userp@ssword
  db:
    url: "jdbc:postgresql://localhost:5432/DOJINLIB?currentSchema=djla"
    userName: "user"
    password: "localuserpass"



  jwt:
    audience: jwt-audience
    domain: http://localhost:5000/ap-northeast-1_bdd640fb06674ad19c80317fa3b1799d/.well-known/jwks.json
    realm: ktor sample app
    secret: secret